# This file contains configuration flags to customize your site
#

avatar: /images/logo-goldB.jpg
email: hualin@okstate.edu
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Name of your site (displayed in the header)
name: Hua Lin's Webpage

# Short bio or description (displayed in the header)
description: 


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://hualin-ok.github.io


permalink: /:title/

